import { ArrowRight, CalendarDays, GitBranch, KeyRound, UsersRound } from 'lucide-react'
import { useState } from 'react'
import { BrandLogo } from '../layout/BrandLogo'
import { isValidJoinCode, normalizeJoinInput } from '../../join/joinCode'

export function PublicHomepage({ onSignIn }: { onSignIn: () => void }) {
  const [join, setJoin] = useState(''); const [error, setError] = useState<string>()
  function continueJoin() { const code = normalizeJoinInput(join); if (!isValidJoinCode(code)) return setError('Mã gồm 8 ký tự, có chữ hoa, chữ thường và chữ số.'); window.history.pushState({}, '', `/join/${code}`); onSignIn() }
  return <main className="public-homepage"><header className="public-header"><BrandLogo /><nav aria-label="Điều hướng chính"><a href="#features">Tính năng</a><a href="#privacy">Quyền riêng tư</a><button className="text-action" onClick={onSignIn}>Đăng nhập</button></nav></header><section className="public-hero"><div className="hero-copy"><span className="eyebrow">Gia phả của gia đình bạn</span><h1>Giữ người thân gần nhau, qua nhiều thế hệ.</h1><p>Famnesia giúp gia đình ghi lại tên, ngày quan trọng và những mối quan hệ làm nên câu chuyện riêng — với quyền riêng tư được thiết kế theo từng người.</p><div className="hero-actions"><button className="primary-button" onClick={onSignIn}>Tạo gia đình mới <ArrowRight size={16} /></button><div className="join-box"><label htmlFor="public-join">Nhập mã hoặc link gia đình</label><div><input id="public-join" value={join} onChange={(event) => { setJoin(event.target.value); setError(undefined) }} placeholder="aB3cD4eF" /><button className="secondary-button" onClick={continueJoin}>Tham gia</button></div>{error && <small className="form-error">{error}</small>}</div></div></div><div className="lineage-hero" aria-label="Minh họa nhánh gia đình"><span className="lineage-root">Ông bà</span><i /><div><span>Cha mẹ</span><span>Con cháu</span></div><i /><div><span>Những câu chuyện</span><span>Ngày quan trọng</span></div></div></section><section id="features" className="public-values"><span className="eyebrow">Năm điều cốt lõi</span><div className="public-value-grid"><article><KeyRound /><h2>Riêng tư theo từng người</h2><p>Trường contact và ghi chú riêng đi theo quyền được cấp, không chỉ ẩn bằng giao diện.</p></article><article><GitBranch /><h2>Hiểu đúng quan hệ Việt</h2><p>Họ nội, họ ngoại, vai vế và nhiều thế hệ trong một cây thống nhất.</p></article><article><CalendarDays /><h2>Ghi nhớ ngày quan trọng</h2><p>Sinh nhật, ngày giỗ và lịch âm/dương với độ chính xác được giữ nguyên.</p></article><article><UsersRound /><h2>Cùng gia đình cập nhật</h2><p>Owner, editor và viewer với lịch sử thay đổi rõ ràng.</p></article><article><ArrowRight /><h2>Dữ liệu thuộc về gia đình</h2><p>Import và export JSON, Excel, GEDCOM theo policy quyền xuất dữ liệu.</p></article></div></section><section id="privacy" className="public-privacy"><span className="eyebrow">Nói rõ về bảo mật</span><h2>Famnesia hỗ trợ mã hóa theo user cho workspace đã bật bảo vệ.</h2><p>Ứng dụng không tuyên bố “zero knowledge tuyệt đối”, không ngăn người đã được phép xem tự sao chép, và luôn nói rõ khi mất recovery key có thể làm dữ liệu không thể phục hồi.</p></section><footer className="public-footer"><span>Famnesia · dữ liệu gia đình, do gia đình giữ</span><span>Phiên bản local/Preview · Không tải dữ liệu gia đình trên trang công khai</span></footer></main>
}
